### ISSUE TITLE
Опциональное отключение инвертирования изображений

### ISSUE THREAD

**Issue by kmx236** [keyten/HES#30]
Было бы удобно отключать инвертирование изображений, т.к. оно распространяется не только на прозрачные текстовые изображения, но и на другие картинки, что иногда вводит в заблуждение или ухудшает восприятие информации.

**Comment by extempl** [comment]
@kmx236 оно распространяется не только на прозрачные изображения by design, это просто незадокументировано. Оно так же распространяется на крайне тёмные картинки без прозрачности и очень яркие картинки с преобладающим белым цветом (фоном как правило, тот же текст, графики).
Но да, согласен, что есть ложные срабатывания, думал изначально добавить кнопку к каждой инвертированной картинке "отключить инвертирование".
Пока руки не добрались.

**Comment by kmx236** [comment]
Спасибо что ответили!
Думаю что отключение инвертирования через кнопку на каждой инвертированной картинке имеет смысл при включенной опции "Инвертировать изображения", а хотелось бы иметь возможность просто её отключить, т.к. вполне устраивает уровень стандартного затемнения изображений и видео. 

Инвертирование изображений достаточно серьезное вмешательство и хотелось бы иметь возможность его вкл/выкл.

**Comment by extempl** [comment]
@kmx236 2440db2
Добавил опцию в модуль night mode.
